
import java.awt.HeadlessException;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import util.Constantes;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Familia
 */
public class Presentador extends javax.swing.JFrame {

    /**
     * Creates new form Presentador
     */
    public Presentador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        tematicaPresentador = new javax.swing.JComboBox();
        complejidadPresentador = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaPresentador = new javax.swing.JTable();
        consultar = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jCheckBox1.setText("Respuesta correcta");

        tematicaPresentador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Seleccione ---", "historia", "geografia", "matematicas" }));

        complejidadPresentador.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--- Seleccione ---", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        jButton1.setText("SALIR");

        tablaPresentador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pregunta", "Rta Correcta", "Rta Incorrecta 1", "Rta Incorrecta 2", "Rta Incorrecta 3", "Complejidad"
            }
        ));
        jScrollPane2.setViewportView(tablaPresentador);

        consultar.setText("Consultar");
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(376, 376, 376))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(tematicaPresentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(complejidadPresentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jCheckBox1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(consultar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tematicaPresentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(complejidadPresentador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(consultar)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        DefaultTableModel model = (DefaultTableModel) tablaPresentador.getModel();

        String strTematica = tematicaPresentador.getSelectedItem().toString();
        String strComplejidad = complejidadPresentador.getSelectedItem().toString();

        try {
            String cadena;
            File file;
            FileReader f;
            BufferedReader b;
            while (model.getRowCount() > 0) {
                model.removeRow(0);
            }

            if (!strTematica.equals("--- Seleccione ---") && strComplejidad.equals("--- Seleccione ---")) {
                String ruta = Constantes.URL.concat(strTematica).concat(Constantes.EXTENSION_ARCHIVO);
                file = new File(ruta);
                if (file.exists()) {
                    f = new FileReader(ruta);
                    b = new BufferedReader(f);
                    while ((cadena = b.readLine()) != null) {
                        if (!cadena.trim().equals("")) {
                            String[] pregunta = cadena.split(",");
                            model.addRow(new Object[]{pregunta[0], pregunta[1], pregunta[2], pregunta[3], pregunta[4], pregunta[5]});
                        }
                    }
                    b.close();
                    f.close();
                }
            } else if (strTematica.equals("--- Seleccione ---") && !strComplejidad.equals("--- Seleccione ---")) {
                int tamTematica = tematicaPresentador.getItemCount();
                for (int i = 1; i < tamTematica; i++) {
                    Object obj = tematicaPresentador.getItemAt(i);
                    String ruta = Constantes.URL.concat(obj.toString()).concat(Constantes.EXTENSION_ARCHIVO);
                    file = new File(ruta);
                    if (file.exists()) {
                        f = new FileReader(ruta);
                        b = new BufferedReader(f);
                        while ((cadena = b.readLine()) != null) {
                            if (!cadena.trim().equals("")) {
                                String[] pregunta = cadena.split(",");
                                if (pregunta[5].trim().equals(strComplejidad)) {
                                    model.addRow(new Object[]{pregunta[0], pregunta[1], pregunta[2], pregunta[3], pregunta[4], pregunta[5]});
                                }
                            }
                        }
                        b.close();
                        f.close();
                    }
                }
            } else if (!strTematica.equals("--- Seleccione ---") && !strComplejidad.equals("--- Seleccione ---")) {
                String ruta = Constantes.URL.concat(strTematica).concat(Constantes.EXTENSION_ARCHIVO);
                file = new File(ruta);
                if (file.exists()) {
                    f = new FileReader(ruta);
                    b = new BufferedReader(f);
                    while ((cadena = b.readLine()) != null) {
                        if (!cadena.trim().equals("")) {
                            String[] pregunta = cadena.split(",");
                            if (pregunta[5].trim().equals(strComplejidad)) {
                                model.addRow(new Object[]{pregunta[0], pregunta[1], pregunta[2], pregunta[3], pregunta[4], pregunta[5]});
                            }
                        }
                    }
                    b.close();
                    f.close();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Debe escoger almenos un filtro.");
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(null, "No se pudo crear el archivo: "
                    + strTematica.concat(Constantes.EXTENSION_ARCHIVO) + " porque:" + e.getMessage());
        }
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Presentador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Presentador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Presentador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Presentador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Presentador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox complejidadPresentador;
    private javax.swing.JButton consultar;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable tablaPresentador;
    private javax.swing.JComboBox tematicaPresentador;
    // End of variables declaration//GEN-END:variables
}
